var graduates =[	

{firstName: 'Mark', lastName: 'Anderson', year: '2016', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Adam', lastName: 'Aschenbrenner', year: '2016', job: 'Teacher', employer: 'Lincoln Southwest', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68, picture: ''},
{firstName: 'Matthew', lastName: 'Chapa', year: '2016', job: 'Teacher', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Michael', lastName: 'Grau', year: '2016', job: 'Graduate Student in Mechanical Engineering', employer: 'NYU Tandon School of Engineering', blurb: '', city: 'Brooklyn', state: 'NY', latitude: 40.64, longitude: -73.94, picture: ''},
{firstName: 'Madison', lastName: 'Hawkins', year: '2016', job: 'Teacher', employer: 'Prince of Peace', blurb: '', city: 'Fremont', state: 'CA', latitude: 37.56, longitude: -121.98, picture: ''},
{firstName: 'Mary', lastName: 'Hietala', year: '2016', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Thomas', lastName: 'Hinrichs', year: '2016', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Luke', lastName: 'Kaldahl', year: '2016', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Justin', lastName: 'Kathman', year: '2016', job: 'Teacher', employer: 'Washburn Rural Middle School', blurb: '', city: 'Topeka', state: 'KS', latitude: 39.03, longitude: -95.69, picture: 'justinkathman.jpg'},
{firstName: 'Justin', lastName: 'Lawrie', year: '2016', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Matt', lastName: 'Meisinger', year: '2016', job: 'Accountant', employer: 'HSMC Orizon', blurb: '', city: 'Omaha', state: 'NE', latitude: 41.26, longitude: -96.01, picture: 'mattmeisinger.jpg'},
{firstName: 'Erika', lastName: 'Schroeder', year: '2016', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Benjamin', lastName: 'Schulteis', year: '2016', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Marcelino (Obed)', lastName: 'VaronaOrtiz', year: '2016', job: 'Graduate Student in Chemistry', employer: 'Iowa State University', blurb: '', city: 'Ames', state: 'IA', latitude: 42.02, longitude: -93.62, picture: ''},
{firstName: 'Erin', lastName: 'Cernik', year: '2015', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Colin', lastName: 'Elley', year: '2015', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Devin', lastName: 'Elley', year: '2015', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Erica', lastName: 'Ellis', year: '2015', job: 'Chemist', employer: 'Hill Air Force Base', blurb: '', city: 'Ogden', state: 'UT', latitude: 41.24, longitude: -111.99, picture: 'ericaellis.jpg'},

{firstName: 'Brittany', lastName: 'Erdmann', year: '2015', job: 'Teacher', employer: 'Lutheran High School West', blurb: '', city: 'Rocky River', state: 'OH', latitude: 41.47, longitude: -81.85, picture: 'brittanyerdmann.jpg'},
{firstName: 'Angelique', lastName: 'Feemster', year: '2015', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Anthony', lastName: 'Fisher', year: '2015', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Hannah', lastName: 'Hester', year: '2015', job: 'Teaching English, Theology, American Geography', employer: 'CELA', blurb: '', city: 'ChiaYi', state: 'Taiwan', latitude: 0, longitude: 0, picture: ''},

{firstName: 'Kelsey', lastName: 'Hizer', year: '2015', job: 'Teacher', employer: 'Lutheran High School', blurb: '', city: 'Parker', state: 'CO', latitude: 39.5, longitude: -104.76, picture: 'kelseyhizer.jpg'},
{firstName: 'Adison', lastName: 'Kenning', year: '2015', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Keith', lastName: 'Kettner', year: '2015', job: 'Seminary Student', employer: 'Concordia Theological Seminary', blurb: '', city: 'Fort Wayne', state: 'IN', latitude: 41.07, longitude: -85.13, picture: 'keithkettner.jpg'},
{firstName: 'Natalie', lastName: 'Lehenbauer', year: '2015', job: 'Benefits Calculation Administrator', employer: 'Aon Hewitt', blurb: '', city: 'Orlando', state: 'FL', latitude: 28.5, longitude: -81.37, picture: ''},
{firstName: 'Anna', lastName: 'McDaniel', year: '2015', job: 'Teacher', employer: 'Faith Lutheran High School', blurb: '', city: 'Las Vegas', state: 'NV', latitude: 36.17, longitude: -115.12, picture: ''},
{firstName: 'Brian', lastName: 'Quinn', year: '2015', job: 'Graduate Student <br> Football Coach', employer: 'Concordia University', blurb: '', city: 'Seward', state: 'NE', latitude: 40.91, longitude: -97.09, picture: ''},
{firstName: 'Ann', lastName: 'Schmidt', year: '2015', job: 'Software Development Engineer', employer: 'Lexmark', blurb: '', city: 'Lenexa', state: 'KS', latitude: 38.9, longitude: -94.68, picture: ''},
{firstName: 'Brett', lastName: 'Shaw', year: '2015', job: 'Graduate Student <br> MAT in Mathematics', employer: 'University of Nebraska', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68, picture: ''},
{firstName: 'Jacob', lastName: 'Toensing', year: '2015', job: 'Teacher', employer: 'St. Paul Lutheran High School', blurb: '', city: 'Concordia', state: 'MO', latitude: 38.98, longitude: -93.56, picture: ''},
{firstName: 'Marty', lastName: 'Trainor', year: '2015', job: 'Law School', employer: '', blurb: '', city: 'Chicago', state: 'IL', latitude: 41.85, longitude: -87.65, picture: ''},
{firstName: 'Adam', lastName: 'Vogt', year: '2015', job: 'Teacher', employer: 'Scotts Bluff High School', blurb: '', city: 'Scotts Bluff', state: 'NE', latitude: 41.86, longitude: -103.66, picture: ''},
{firstName: 'Adam', lastName: 'Vogt', year: '2015', job: 'Teacher', employer: 'Lourdes Central Catholic', blurb: '', city: 'Nebraska City', state: 'NE', latitude: 40.67, longitude: -95.86, picture: ''},
{firstName: 'Brandon', lastName: 'Wood', year: '2015', job: 'Building and Inspection Department', employer: 'City of Seward', blurb: '', city: 'Seward', state: 'NE', latitude: 40.91, longitude: -97.09, picture: ''},

{firstName: 'Andrew', lastName: 'Yerrell', year: '2015', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Nathan', lastName: 'Douglas', year: '2014', job: '', employer: 'Sandhills Publishing', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68, picture: ''},
{firstName: 'Douglas', lastName: 'Erickson', year: '2014', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Andy', lastName: 'Hammes', year: '2014', job: 'Graduate Student in BioStatistics', employer: 'University of Colorado', blurb: '', city: 'Denver', state: 'CO', latitude: 39.76, longitude: -104.87, picture: 'andyhammes.jpg'},
{firstName: 'Faith', lastName: 'Hoppen', year: '2014', job: 'Teacher', employer: 'Black Hills Lutheran', blurb: '', city: 'Rapid City', state: 'SD', latitude: 44.07, longitude: -103.23, picture: 'faithhoppen.jpg'},
{firstName: 'Eric', lastName: 'Hyde', year: '2014', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jillian', lastName: 'Jensen', year: '2014', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jacob', lastName: 'Krings', year: '2014', job: 'Software Developer', employer: 'Agilx', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68, picture: ''},

{firstName: 'Sarah', lastName: 'Mack', year: '2014', job: 'Teacher', employer: 'Central City High School', blurb: '', city: 'Central City', state: 'NE', latitude: 41.11, longitude: -98, picture: ''},
{firstName: 'Nathanael', lastName: 'Pfeil', year: '2014', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jon', lastName: 'Richters', year: '2014', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Ethan', lastName: 'Utecht', year: '2014', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Angela', lastName: 'Bruhn', year: '2013', job: 'Teacher', employer: 'Lyons-Decatur Northeast High School', blurb: '', city: 'Lyons', state: 'NE', latitude: 41.93, longitude: -96.47, picture: ''},
{firstName: 'Preston', lastName: 'Doerr', year: '2013', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Eric', lastName: 'Fox', year: '2013', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Daniel', lastName: 'Geu', year: '2013', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Daniel', lastName: 'Gibson', year: '2013', job: 'Teacher', employer: 'Lutheran School Association', blurb: '', city: 'Decatur', state: 'IL', latitude: 39.85, longitude: -88.93, picture: 'dangibson.jpg'},

{firstName: 'Marcus', lastName: 'Gubanyi', year: '2013', job: 'Graduate Student in Mathematics', employer: 'Kansas Univeristy', blurb: '', city: 'Lawrence', state: 'KS', latitude: 38.96, longitude: -95.25, picture: 'marcusgubanyi.jpg'},
{firstName: 'Alexa', lastName: 'Hopping', year: '2013', job: 'Volleyball Coach', employer: 'Mid Plains Community College', blurb: '', city: 'North Platte', state: 'NE', latitude: 41.13, longitude: -100.77, picture: ''},
{firstName: 'Kyle', lastName: 'Ivanoff', year: '2013', job: 'Teacher', employer: 'Mountain View High School', blurb: '', city: 'Tucson', state: 'AZ', latitude: 32.21, longitude: -110.96, picture: ''},

{firstName: 'Connie', lastName: 'Triplett (Kettner)', year: '2013', job: 'Teacher', employer: 'Bethany Lutheran School', blurb: '', city: 'Parma', state: 'OH', latitude: 41.47, longitude: -81.67, picture: ''},
{firstName: 'Daniel', lastName: 'Klinge', year: '2013', job: 'Nuclear Engineer on a Submarine', employer: 'US Navy', blurb: '', city: 'Newport', state: 'RI', latitude: 41.47, longitude: -71.3, picture: 'danielklinge.jpg'},
{firstName: 'Samantha', lastName: 'Lafontaine', year: '2013', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Dawn', lastName: 'Martin', year: '2013', job: 'Teacher', employer: 'Lutheran High South', blurb: '', city: 'Saint Louis', state: 'MO', latitude: 38.63, longitude: -90.24, picture: ''},

{firstName: 'Danielle', lastName: 'Masur', year: '2013', job: 'Teacher', employer: 'Scotus Central Catholic', blurb: '', city: 'Columbus', state: 'NE', latitude: 41.43, longitude: -97.35, picture: 'danimasur.jpg'},
{firstName: 'Cory', lastName: 'Prelerson', year: '2013', job: 'Associate System Administrator', employer: 'Leidos/Lockheed Martin', blurb: '', city: 'Redmond', state: 'WA', latitude: 47.68, longitude: -122.12, picture: 'coryprelerson.jpg'},


{firstName: 'Katie', lastName: 'Prelerson (Bergt)', year: '2013', job: 'Teacher', employer: 'Nicola Tesla STEM School', blurb: '', city: 'Redmond', state: 'WA', latitude: 47.68, longitude: -122.12, picture: 'kathleenbergt.jpg'},
{firstName: 'Andrew', lastName: 'Schwartz', year: '2013', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Kristen', lastName: 'Shavlik', year: '2013', job: 'Graduate Student in Mathematics', employer: 'University of Wyoming', blurb: '', city: 'Laramie', state: 'WY', latitude: 41.31, longitude: -105.58, picture: 'kristinshavlik.jpg'},
{firstName: 'Laura', lastName: 'Smith (Jeppesen)', year: '2013', job: 'Teacher', employer: 'Heartland Community Schools', blurb: '', city: 'Henderson', state: 'NE', latitude: 40.77, longitude: -97.81, picture: ''},
{firstName: 'Jordan', lastName: 'Stirtz', year: '2013', job: 'Teacher', employer: 'Papilion South High School', blurb: '', city: 'Omaha', state: 'NE', latitude: 41.26, longitude: -96.01, picture: ''},
{firstName: 'Zackary', lastName: 'Warner', year: '2013', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Heidi', lastName: 'Wilkinson', year: '2013', job: 'Teacher', employer: 'Lighthouse Christian Academy', blurb: '', city: 'Bloomington', state: 'IN', latitude: 39.16, longitude: -86.52, picture: ''},
{firstName: 'Rachel', lastName: 'Brainard', year: '2012', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Alex', lastName: 'Deeter', year: '2012', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Byron', lastName: 'Dow', year: '2012', job: 'Worship Leader', employer: '', blurb: '', city: 'Atlanta', state: 'GA', latitude: 33.85, longitude: -84.39, picture: 'byrondow.jpg'},
{firstName: 'Lauren', lastName: 'Eickmeyer', year: '2012', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Seth', lastName: 'Elley', year: '2012', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Danny', lastName: 'Frastaci', year: '2012', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: 'dannyfrastaci.jpg'},
{firstName: 'Taylor', lastName: 'Friedel', year: '2012', job: 'Teacher', employer: 'Faith Lutheran High School', blurb: '', city: 'Las Vegas', state: 'NV', latitude: 36.17, longitude: -115.12, picture: ''},
{firstName: 'Jeremy', lastName: 'Jank', year: '2012', job: 'Graduate Student <br> MAT in Mathematics', employer: 'University of Nebraska', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68, picture: 'jeremyjank.jpg'},
{firstName: 'Mikaela', lastName: 'Klein', year: '2012', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jonathan', lastName: 'Laufer', year: '2012', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Tory', lastName: 'Petz', year: '2012', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jonathan', lastName: 'Rempfer', year: '2012', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Matthew', lastName: 'Schranz', year: '2012', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},

{firstName: 'Nathan', lastName: 'Sindt', year: '2012', job: 'Graduate Student in Molecular Biology', employer: 'Colorado State University', blurb: '', city: 'Fort Collins', state: 'CO', latitude: 40.55, longitude: -105.06, picture: ''},
{firstName: 'Jesse', lastName: 'Skelton', year: '2012', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Brett', lastName: 'Troyer', year: '2012', job: 'Teacher', employer: 'Crete High School', blurb: '', city: 'Crete', state: 'NE', latitude: 40.62, longitude: -96.95, picture: ''},

{firstName: 'Lindsey', lastName: 'Warneke', year: '2012', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Brenton', lastName: 'Whitaker', year: '2012', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Katelin', lastName: 'Austin', year: '2011', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Katelin', lastName: 'Daletas', year: '2011', job: 'Teacher', employer: 'Grace Lutheran', blurb: '', city: 'Pocatello', state: 'ID', latitude: 42.9, longitude: -112.39, picture: ''},
{firstName: 'Debra', lastName: 'Erickson', year: '2011', job: 'Teacher', employer: 'St. Paul Lutheran School', blurb: '', city: 'Fort Dodge', state: 'IA', latitude: 42.5, longitude: -94.17, picture: ''},
{firstName: 'Abby', lastName: 'Klein', year: '2011', job: 'Teacher', employer: 'East Butler Consolidated Schools', blurb: '', city: 'Brainard', state: 'NE', latitude: 41.18, longitude: -97, picture: ''},
{firstName: 'Antoine', lastName: 'Love', year: '2011', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Ben', lastName: 'Mann', year: '2011', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Andrew', lastName: 'Rogers', year: '2011', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Luann', lastName: 'Scheufele (Jacobitz)', year: '2011', job: 'Teacher', employer: 'Lutheran Elementary School', blurb: '', city: 'San Angelo', state: 'TX', latitude: 31.44, longitude: -100.45, picture: ''},

{firstName: 'Sally', lastName: 'Schwarz', year: '2011', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Raymond', lastName: 'Spiering', year: '2011', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Brett', lastName: 'Waite', year: '2011', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Sarah', lastName: 'Weber', year: '2011', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Travis', lastName: 'Besel', year: '2010', job: 'Teacher', employer: 'Word of Life Lutheran School', blurb: '', city: 'Saint Louis', state: 'MO', latitude: 38.63, longitude: -90.24, picture: ''},
{firstName: 'Allison', lastName: 'Chrismer', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Matthew', lastName: 'Foster', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Zane', lastName: 'Grabau', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Joel', lastName: 'Henschen', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Daniel', lastName: 'Kober', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jonathan', lastName: 'McDaniel', year: '2010', job: 'Teacher', employer: 'Faith Lutheran High School', blurb: '', city: 'Las Vegas', state: 'NV', latitude: 36.17, longitude: -115.12, picture: ''},
{firstName: 'Rebecca', lastName: 'Mol', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jared', lastName: 'Olson', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Katherine', lastName: 'Raphelt', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'M\'Leigh', lastName: 'Rempfer', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Drew', lastName: 'Rodine', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Kurt', lastName: 'Rutz', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Daniel', lastName: 'Uden', year: '2010', job: 'Graduate Student in Natural Resource Sciences', employer: 'University of Nebraska', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68, picture: ''},
{firstName: 'Ashley', lastName: 'Ahlman', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Craig', lastName: 'Dannehl', year: '2009', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Melissa', lastName: 'Edmiston', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Barry', lastName: 'Eitzmann', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Matthew', lastName: 'Gerhart', year: '2009', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Christie', lastName: 'Hampton', year: '2009', job: 'Teacher/Admissions Director', employer: 'Lutheran High School of Indianapolis', blurb: '', city: 'Indianapolis', state: 'IN', latitude: 39.77, longitude: -86.14, picture: ''},
{firstName: 'Jordan', lastName: 'Hinrichs', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Angela', lastName: 'Ivie', year: '2009', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Daniel', lastName: 'Jansen', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Nathaniel', lastName: 'Meyer', year: '2009', job: 'Graduate Student in Statistics', employer: 'University of Nebraska', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68, picture: ''},
{firstName: 'Andrew', lastName: 'Raphelt', year: '2009', job: 'Graduate Student in Chemistry', employer: 'University of Texas', blurb: '', city: 'Austin', state: 'TX', latitude: 30.26, longitude: -97.74, picture: ''},
{firstName: 'Jessica', lastName: 'Ripke', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Todd', lastName: 'Stahlecker', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Angela', lastName: 'Weinhold', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jesse', lastName: 'Wisroth', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Richard', lastName: 'Backhus', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Elizabeth', lastName: 'Brisbois', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Gregory', lastName: 'Gustad', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'David', lastName: 'Jabs', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Kyle', lastName: 'Johnson', year: '2008', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Christine', lastName: 'Mabrey', year: '2008', job: 'Teacher', employer: 'Emmanuel Lutheran School', blurb: '', city: 'Asheville', state: 'NC', latitude: 35.57, longitude: -82.54, picture: ''},
{firstName: 'Brett', lastName: 'Mertens', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Marcus', lastName: 'Nathan', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Kristen', lastName: 'Newell (Peters)', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jackie', lastName: 'Nuxoll', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Joshua', lastName: 'Olson', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jared', lastName: 'Oswald', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Ryan', lastName: 'Zulkoski', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Rebecca', lastName: 'Anderson', year: '2007', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Brent', lastName: 'Bejot', year: '2007', job: 'Graduate Student in Computer Science', employer: 'University of Illinois', blurb: '', city: 'Chicago', state: 'IL', latitude: 41.85, longitude: -87.65, picture: ''},
{firstName: 'Matthew', lastName: 'Egger', year: '2007', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Dean', lastName: 'Flaten', year: '2007', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Mallary', lastName: 'Gunnare', year: '2007', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jonathan', lastName: 'Kern', year: '2007', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Heidi', lastName: 'Miller', year: '2007', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Trevor', lastName: 'Osten', year: '2007', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Rachel', lastName: 'Reeves', year: '2007', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jacob', lastName: 'Schmidt', year: '2007', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jonathan', lastName: 'Whitson', year: '2007', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Harlan', lastName: 'Anson', year: '2006', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Daniel', lastName: 'Bergquist', year: '2006', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Hans', lastName: 'Boeschen', year: '2006', job: 'Graduate Student in Industrial Engineering', employer: 'University of Nebraska', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68, picture: ''},
{firstName: 'Mindy', lastName: 'Brunkhardt', year: '2006', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Sadie', lastName: 'Daake', year: '2006', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Kelly', lastName: 'Dawson', year: '2006', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Justin', lastName: 'Eld', year: '2006', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Alissa', lastName: 'Heinecke', year: '2006', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Daniel', lastName: 'Jabs', year: '2006', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Elizabeth', lastName: 'Jabs', year: '2006', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jennifer', lastName: 'Karner', year: '2006', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jamie', lastName: 'Kootz (Burmeister)', year: '2006', job: 'Instructor and Graduate Student', employer: 'MNU and KWU', blurb: '', city: 'Salina', state: 'KS', latitude: 38.81, longitude: -97.61, picture: ''},
{firstName: 'Lisa', lastName: 'Matthis', year: '2006', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jennifer', lastName: 'McBride', year: '2006', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Katie', lastName: 'Nelson', year: '2006', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Lisa', lastName: 'Ochs', year: '2006', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jacqueline', lastName: 'Ott', year: '2006', job: 'Graduate Student in Biology', employer: 'Kansas State Univesity', blurb: '', city: 'Manhattan', state: 'KS', latitude: 39.19, longitude: -96.59, picture: ''},
{firstName: 'Kalika', lastName: 'Peske', year: '2006', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Kristin', lastName: 'Schmidt', year: '2006', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jennifer', lastName: 'Schwartz (Davis)', year: '2006', job: 'Graduate Student in Biometry', employer: 'University of Nebraska', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68, picture: ''},
{firstName: 'Matthew', lastName: 'Steiner', year: '2006', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Derek', lastName: 'Bult', year: '2005', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Derek', lastName: 'Bult', year: '2005', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Lisa', lastName: 'Burger', year: '2005', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Janine', lastName: 'Case', year: '2005', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Amy', lastName: 'Cooper', year: '2005', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jennifer', lastName: 'Dixon', year: '2005', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Katherine', lastName: 'Doroh', year: '2005', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Karen', lastName: 'Duke', year: '2005', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Matthew', lastName: 'Haden', year: '2005', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Rebecca', lastName: 'Jabs', year: '2005', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Mirinda', lastName: 'Krenz (Chavet)', year: '2005', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Kristin', lastName: 'Lee', year: '2005', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Meredith', lastName: 'Marsh', year: '2005', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Montica', lastName: 'Minard', year: '2005', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Jennifer', lastName: 'Ockinga', year: '2005', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Michelle', lastName: 'Quinlan', year: '2005', job: 'Graduate Student in Statistics', employer: 'University of Nebraska', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68, picture: ''},
{firstName: 'Pamela', lastName: 'Sawusch', year: '2005', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Leah', lastName: 'Steinbronn', year: '2005', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Darin', lastName: 'Suckstorf', year: '2005', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},
{firstName: 'Lydia', lastName: 'Tirrel', year: '2005', job: 'X', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0, picture: ''},


];