var graduates =[	
{firstName: 'Brittany', lastName: 'Erdmann', year: '2015', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Kelsey', lastName: 'Hizer', year: '2015', job: 'Teacher', employer: 'Lutheran High School', blurb: '', city: 'Parker', state: 'CO', latitude: 39.5, longitude: -104.76},
{firstName: 'Justin', lastName: 'Kathman', year: '2016', job: 'Teacher', employer: 'Washburn Rural Middle School', blurb: '', city: 'Topeka', state: 'KS', latitude: 39.03, longitude: -95.69},
{firstName: 'Matt', lastName: 'Meisinger', year: '2016', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Brett', lastName: 'Shaw', year: '2015', job: 'Graduate Student <br> MAT in Mathematics', employer: 'University of Nebraska', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68},
{firstName: 'Marty', lastName: 'Trainor', year: '2015', job: 'Law School', employer: '', blurb: '', city: 'Chicago', state: 'IL', latitude: 41.85, longitude: -87.65},
{firstName: 'Ann', lastName: 'Schmidt', year: '2015', job: 'Software Development Engineer', employer: 'Lexmark', blurb: '', city: 'Lenexa', state: 'KS', latitude: 38.9, longitude: -94.68},
{firstName: 'Hannah', lastName: 'Hester', year: '2015', job: 'Teaching English', employer: 'CELA', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Jacob', lastName: 'Toensing', year: '2015', job: 'Teacher', employer: 'St. Paul Lutheran High School', blurb: '', city: 'Concordia', state: 'MO', latitude: 38.98, longitude: -93.56},
{firstName: 'Erica', lastName: 'Ellis', year: '2015', job: 'Chemist', employer: 'Hill Air Force Base', blurb: '', city: 'Ogden', state: 'UT', latitude: 41.24, longitude: -111.99},
{firstName: 'Natalie', lastName: 'Lehenbauer', year: '2015', job: 'Benefits Calculation Administrator', employer: 'Aon Hewitt', blurb: '', city: 'Orlando', state: 'FL', latitude: 28.5, longitude: -81.37},
{firstName: 'Brian', lastName: 'Quinn', year: '2015', job: 'Graduate Student <br> Football Coach', employer: 'Concordia University', blurb: '', city: 'Seward', state: 'NE', latitude: 40.91, longitude: -97.09},
{firstName: 'Brandon', lastName: 'Wood', year: '2015', job: 'Building and Inspection Department', employer: 'City of Seward', blurb: '', city: 'Seward', state: 'NE', latitude: 40.91, longitude: -97.09},
{firstName: 'Keith', lastName: 'Kettner', year: '2015', job: 'Seminary Student', employer: 'Concordia Theological Seminary', blurb: '', city: 'Fort Wayne', state: 'IN', latitude: 41.07, longitude: -85.13},
{firstName: 'Adam', lastName: 'Vogt', year: '2015', job: 'Teacher', employer: 'Scotts Bluff High School', blurb: '', city: 'Scotts Bluff', state: 'NE', latitude: 41.86, longitude: -103.66},
{firstName: 'Adam', lastName: 'Vogt', year: '2015', job: 'Teacher', employer: 'Lourdes Central Catholic', blurb: '', city: 'Nebraska City', state: 'NE', latitude: 40.67, longitude: -95.86},
{firstName: 'Erin', lastName: 'Cernik', year: '2015', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Colin', lastName: 'Elley', year: '2015', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Devin', lastName: 'Elley', year: '2015', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Anthony', lastName: 'Fisher', year: '2015', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Andrew', lastName: 'Yerrell', year: '2015', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Andy', lastName: 'Hammes', year: '2014', job: 'Graduate Student in BioStatistics', employer: 'University of Colorado', blurb: '', city: 'Denver', state: 'CO', latitude: 39.76, longitude: -104.87},
{firstName: 'Jacob', lastName: 'Krings', year: '2014', job: 'Software Developer', employer: 'Agilx', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68},
{firstName: 'Jon', lastName: 'Richters', year: '2014', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Nathan', lastName: 'Douglas', year: '2014', job: '', employer: 'Sanhills Publishing', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68},
{firstName: 'Faith', lastName: 'Hoppen', year: '2014', job: 'Teacher', employer: 'Black Hills Lutheran', blurb: '', city: 'Rapid City', state: 'SD', latitude: 44.07, longitude: -103.23},
{firstName: 'Sarah', lastName: 'Mack', year: '2014', job: 'Teacher', employer: 'Central City High School', blurb: '', city: 'Central City', state: 'NE', latitude: 41.11, longitude: -98},
{firstName: 'Marcus', lastName: 'Gubanyi', year: '2013', job: 'Graduate Student in Mathematics', employer: 'Kansas Univeristy', blurb: '', city: 'Lawrence', state: 'KS', latitude: 38.96, longitude: -95.25},
{firstName: 'Jordan', lastName: 'Stirtz', year: '2013', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Preston', lastName: 'Doerr', year: '2013', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Kyle', lastName: 'Ivanoff', year: '2013', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Andrew', lastName: 'Schwartz', year: '2013', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Kristen', lastName: 'Shavlik', year: '2013', job: 'Graduate Student in Mathematics', employer: 'University of Wyoming', blurb: '', city: 'Laramie', state: 'WY', latitude: 41.31, longitude: -105.58},
{firstName: 'Daniel', lastName: 'Geu', year: '2013', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Heidi', lastName: 'Wilkinson', year: '2013', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Alexa', lastName: 'Hopping', year: '2013', job: 'Volleyball Coach', employer: 'Mid Plains Community College', blurb: '', city: 'North Platte', state: 'NE', latitude: 41.13, longitude: -100.77},
{firstName: 'Danielle', lastName: 'Masur', year: '2013', job: 'Teacher', employer: 'Scotus Central Catholic', blurb: '', city: 'Columbus', state: 'NE', latitude: 41.43, longitude: -97.35},
{firstName: 'Daniel', lastName: 'Klinge', year: '2013', job: 'Nuclear Engineer on a Submarine', employer: 'US Navy', blurb: '', city: 'Newport', state: 'RI', latitude: 41.47, longitude: -71.3},
{firstName: 'Daniel', lastName: 'Gibson', year: '2013', job: 'Teacher', employer: 'Lutheran School Association', blurb: '', city: 'Decatur', state: 'IL', latitude: 39.85, longitude: -88.93},
{firstName: 'Laura', lastName: 'Jeppesen', year: '2013', job: 'Teacher', employer: 'Heartland Community Schools', blurb: '', city: 'Henderson', state: 'NE', latitude: 40.77, longitude: -97.81},
{firstName: 'Angela', lastName: 'Bruhn', year: '2013', job: 'Teacher', employer: 'Lyons-Decatur Northeast High School', blurb: '', city: 'Lyons', state: 'NE', latitude: 41.93, longitude: -96.47},
{firstName: 'Katie', lastName: 'Bergt', year: '2013', job: 'Teacher', employer: '', blurb: '', city: 'Redmond', state: 'WA', latitude: 47.68, longitude: -122.12},
{firstName: 'Cory', lastName: 'Prelerson', year: '2013', job: 'Graduate Student', employer: 'DigiPen Institute of Technology', blurb: '', city: 'Redmond', state: 'WA', latitude: 47.68, longitude: -122.12},
{firstName: 'Connie', lastName: 'Kettner', year: '2013', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Dawn', lastName: 'Martin', year: '2013', job: 'Teacher', employer: 'Lutheran High South', blurb: '', city: 'Saint Louis', state: 'MO', latitude: 38.63, longitude: -90.24},
{firstName: 'Samantha', lastName: 'Lafontaine', year: '2013', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Brett', lastName: 'Troyer', year: '2012', job: 'Teacher', employer: 'Crete High School', blurb: '', city: 'Crete', state: 'NE', latitude: 40.62, longitude: -96.95},

{firstName: 'Alex', lastName: 'Deeter', year: '2012', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Tory', lastName: 'Petz', year: '2012', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Byron', lastName: 'Dow', year: '2012', job: 'Worship Leader', employer: '', blurb: '', city: 'Atlanta', state: 'GA', latitude: 33.85, longitude: -84.39},
{firstName: 'Danny', lastName: 'Frastaci', year: '2012', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Taylor', lastName: 'Friedel', year: '2012', job: 'Teacher', employer: 'Faith Lutheran High School', blurb: '', city: 'Las Vegas', state: 'NV', latitude: 36.17, longitude: -115.12},
{firstName: 'Lindsey', lastName: 'Warneke', year: '2012', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Nathan', lastName: 'Sindt', year: '2012', job: 'Graduate Student in Molecular Biology', employer: 'Colorado State University', blurb: '', city: 'Fort Collins', state: 'CO', latitude: 40.55, longitude: -105.06},
{firstName: 'Jeremy', lastName: 'Jank', year: '2012', job: 'Graduate Student <br> MAT in Mathematics', employer: 'University of Nebraska', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68},
{firstName: 'Lauren', lastName: 'Eickmeyer', year: '2012', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Abby', lastName: 'Klein', year: '2011', job: 'Teacher', employer: 'East Butler Consolidated Schools', blurb: '', city: 'Brainard', state: 'NE', latitude: 41.18, longitude: -97},
{firstName: 'Luann', lastName: 'Jacobitz', year: '2011', job: 'Teacher', employer: 'Lutheran Elementary School', blurb: '', city: 'San Angelo', state: 'TX', latitude: 31.44, longitude: -100.45},
{firstName: 'Debra', lastName: 'Erickson', year: '2011', job: 'Teacher', employer: 'St. Paul Lutheran School', blurb: '', city: 'Fort Dodge', state: 'IA', latitude: 42.5, longitude: -94.17},
{firstName: 'Ben', lastName: 'Mann', year: '2011', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Katelin', lastName: 'Daletas', year: '2011', job: 'Teacher', employer: 'Grace Lutheran', blurb: '', city: 'Pocatello', state: 'ID', latitude: 42.9, longitude: -112.39},
{firstName: 'Travis', lastName: 'Bessel', year: '2010', job: 'Teacher', employer: 'Word of Life Lutheran School', blurb: '', city: 'Saint Louis', state: 'MO', latitude: 38.63, longitude: -90.24},
{firstName: 'Zane', lastName: 'Grabau', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Allison', lastName: 'Chrismer', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Matthew', lastName: 'Foster', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Joel', lastName: 'Henschen', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Daniel', lastName: 'Kober', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Jonathan', lastName: 'McDaniel', year: '2010', job: 'Teacher', employer: 'Faith Lutheran High School', blurb: '', city: 'Las Vegas', state: 'NV', latitude: 36.17, longitude: -115.12},
{firstName: 'Rebecca', lastName: 'Mol', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Jared', lastName: 'Olson', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Katherine', lastName: 'Raphelt', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'M\'Leigh', lastName: 'Rempfer', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Drew', lastName: 'Rodine', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Kurt', lastName: 'Rutz', year: '2010', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Daniel', lastName: 'Uden', year: '2010', job: 'Graduate Student in Natural Resource Sciences', employer: 'University of Nebraska', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68},
{firstName: 'Nathaniel', lastName: 'Meyer', year: '2009', job: 'Graduate Student in Statistics', employer: 'University of Nebraska', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68},
{firstName: 'Andrew', lastName: 'Raphelt', year: '2009', job: 'Graduate Student in Chemistry', employer: 'University of Texas', blurb: '', city: 'Austin', state: 'TX', latitude: 30.26, longitude: -97.74},
{firstName: 'Ashley', lastName: 'Ahlman', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Melissa', lastName: 'Edmiston', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Barry', lastName: 'Eitzmann', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Jordan', lastName: 'Hinrichs', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Daniel', lastName: 'Jansen', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Jessica', lastName: 'Ripke', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Todd', lastName: 'Stahlecker', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Angela', lastName: 'Weinhold', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Jesse', lastName: 'Wisroth', year: '2009', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Elizabeth', lastName: 'Brisbois', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Richard', lastName: 'Backhus', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Joshua', lastName: 'Olson', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Gregory', lastName: 'Gustad', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'David', lastName: 'Jabs', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Christine', lastName: 'Mabrey', year: '2008', job: 'Teacher', employer: 'Emmanuel Lutheran School', blurb: '', city: 'Asheville', state: 'NC', latitude: 35.57, longitude: -82.54},
{firstName: 'Brett', lastName: 'Mertens', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Marcus', lastName: 'Nathan', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Kristen', lastName: 'Newell (Peters)', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Jackie', lastName: 'Nuxoll', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Jared', lastName: 'Oswald', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Ryan', lastName: 'Zulkoski', year: '2008', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Brent', lastName: 'Bejot', year: '2007', job: 'Graduate Student in Computer Science', employer: 'University of Illinois', blurb: '', city: 'Chicago', state: 'IL', latitude: 41.85, longitude: -87.65},
{firstName: 'Rachel', lastName: 'Reeves', year: '2007', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Jonathan', lastName: 'Kern', year: '2007', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Matthew', lastName: 'Egger', year: '2007', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Dean', lastName: 'Flaten', year: '2007', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Mallary', lastName: 'Gunnare', year: '2007', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Jonathan', lastName: 'Kern', year: '2007', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Trevor', lastName: 'Osten', year: '2007', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Jacob', lastName: 'Schmidt', year: '2007', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Hans', lastName: 'Boeschen', year: '2006', job: 'Graduate Student in Industrial Engineering', employer: 'University of Nebraska', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68},
{firstName: 'Jacqueline', lastName: 'Ott', year: '2006', job: 'Graduate Student in Biology', employer: 'Kansas State Univesity', blurb: '', city: 'Manhattan', state: 'KS', latitude: 39.19, longitude: -96.59},
{firstName: 'Jennifer', lastName: 'Schwartz (Davis)', year: '2006', job: 'Graduate Student in Biometry', employer: 'University of Nebraska', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68},
{firstName: 'Daniel', lastName: 'Bergquist', year: '2006', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Mindy', lastName: 'Brunkhardt', year: '2006', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Sadie', lastName: 'Daake', year: '2006', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Daniel', lastName: 'Jabs', year: '2006', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Jamie', lastName: 'Kootz', year: '2006', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Jennifer', lastName: 'McBride', year: '2006', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Michelle', lastName: 'Quinlan', year: '2005', job: 'Graduate Student in Statistics', employer: 'University of Nebraska', blurb: '', city: 'Lincoln', state: 'NE', latitude: 40.81, longitude: -96.68},
{firstName: 'Derek', lastName: 'Bult', year: '2005', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Matthew', lastName: 'Haden', year: '2005', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Mirinda', lastName: 'Krenz (Chavet)', year: '2005', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Meredith', lastName: 'Marsh', year: '2005', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
{firstName: 'Leah', lastName: 'Steinbronn', year: '2005', job: '', employer: '', blurb: '', city: '', state: '', latitude: 0, longitude: 0},
];